### ISSUE TITLE
Allow ConnectPacketBuilder to fail

### ISSUE THREAD

**Issue by dimitrov-anasoft** [eclipse-paho/paho.golang#268]
**Is your feature request related to a problem? Please describe.**
We use OAuth tokens for authentication, which are retrieved on demand from a remote service. If the token cannot be retrieved, no connection attempt should be made. The existing reconnection logic ensures that a token request and a subsequent MQTT connection will be attempted in the future.

**Describe the solution you'd like**
The `ConnectPacketBuilder` callback can return an error, which indicates that no connection attempt should be made in the current iteration of the reconnect logic. See [https://github.com/dimitrov-anasoft/paho.golang/tree/feature/allow_connect_packet_builder_to_fail](https://github.com/dimitrov-anasoft/paho.golang/tree/feature/allow_connect_packet_builder_to_fail) for implementation details.

**Comment by MattBrittan** [comment]
Thanks,

Currently `establishServerConnection` "establishes a connection with the MQTT server retrying until successful or the context is cancelled (in which case nil will be returned)". So the current method to abort the process would be to cancel the context (easy to do if your `ConnectPacketBuilder` has access to the context but this could get a little convoluted).

I'm not against your proposed change and would be happy to see a PR. However, if you take this approach, a variety of comments need to be updated to reflect the fact that the process can abort for reasons other than the context (otherwise users expectations will not be valid). For example:

- [here](https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/autopaho/net.go#L41)
- [here](https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/autopaho/auto.go#L307)
- [here](https://github.com/eclipse/paho.golang/blob/f1fe38b0d4b0ad0347176409c5acdef45b2ff337/autopaho/auto.go#L239)

I would suggest that these state that the process aborts when the context is cancelled, or an irrecoverable error occurs. As we are pre v1 a breaking change here is not a big issue (and I can see others wanting this).

Other potential options:
  - We could just allow `ConnectPacketBuilder` to return `nil` and call `cg.OnConnectError` if that happens (enabling the error handler to abort the process if that is what is needed) before checking the context and retrying. This would be non breaking (but error info would be lost).
  - I wonder whether it would be worth having a "fatal" eror type, if this is returned (or, more likely wrapped in another error) the function will abort, otherwise it will continue to try (with delay before retrying etc). This would allow for both temporay errors (cannot get the token right now, but if you retry it might work) and permanent errors.

M

**Comment by dimitrov-anasoft** [comment]
My bad, the TCP connection was still being established. I've reorganised the code a bit. First we build the CONN packet, then if we have a CONN packet, we establish a TCP connection and send the packet.

I don't get the cancelation/abortion discussion. The `ConnectPacketBuilder` is only used in `buildConnectPacket`, which in turn is only used in the connection establishment loop (`establishServerConnection`). Cancelation/abortion should work the same. Being unable to get an OAuth token does not mean that we have to abort the reconnect loop. It is often the case, that on subsequent retries a token can be retrieved.

**Comment by MattBrittan** [comment]
>Cancelation/abortion should work the same.

Sorry - not sure what I was looking at this morning (must have been half asleep!). Based on a quick scan this looks fine (and `OnConnectError` could be used to abort the connection process if neccessary).

**Comment by dimitrov-anasoft** [comment]
Exactly. I will create a pull request. When do you plan to do the next release?

**Comment by MattBrittan** [comment]
> When do you plan to do the next release?

No plans at this point, it really depends on when something significant is added (have a PR I really must get around to reviewing!).

**Comment by ViToni** [comment]
> > When do you plan to do the next release?
> 
> No plans at this point, it really depends on when something significant is added (have a PR I really must get around to reviewing!).

I'd really love to have a release we could test widely. The last release is from February and changes have accumulated.
If there is an outstanding PR it could still go into a later releaase.

**Comment by ViToni** [comment]
@MattBrittan Would you mind createing a release including this change? It would really help reduce load on our broker.

**Comment by MattBrittan** [comment]
Sorry - been busy. I'll try to get a release out shortly. Note that you can just use `go get github.com/eclipse/paho.golang@master` (or specify a hash) to ge the current dev version.

**Comment by MattBrittan** [comment]
Closing this as release issued that incorporates your changes - thanks.
