### ISSUE TITLE
Does the mqtt v5 go client support backward compatibility with the mqtt v3 server?

### ISSUE THREAD

**Issue by AllenZMC** [eclipse-paho/paho.golang#273]
Does the mqtt v5 go client support backward compatibility with the mqtt v3 server?

**Comment by MattBrittan** [comment]
No, and there are no plans to add this because there are enough differences that implementing V3 would require changes to the interface that are likely to make the library more complicated (and most brokers now support V5).

Please search [existing issues](https://github.com/eclipse-paho/paho.golang/issues/89) before raising a new one.
